//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digital_School.Admin {
    
    
    public partial class SiteData {
        
        /// <summary>
        /// SummarySlideShow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Digital_School.User_Control.Summary SummarySlideShow;
        
        /// <summary>
        /// SummaryGallery control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Digital_School.User_Control.Summary SummaryGallery;
        
        /// <summary>
        /// SummaryPost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Digital_School.User_Control.Summary SummaryPost;
        
        /// <summary>
        /// SummaryHistoryContact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Digital_School.User_Control.Summary SummaryHistoryContact;
        
        /// <summary>
        /// SummaryApplication control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Digital_School.User_Control.Summary SummaryApplication;
        
        /// <summary>
        /// SummaryResult control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Digital_School.User_Control.Summary SummaryResult;
    }
}
